name: Build and Upload Binary

on:
    push:
        branches:
            - main
    tags:
        - "*"

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "7.x"

            - name: Restore dependencies
              run: dotnet restore

            - name: Build the project
              run: dotnet build --configuration Release

            - name: Publish the project
              run: dotnet publish --configuration Release --output ./publish

            - name: Upload binary
              uses: actions/upload-artifact@v3
              with:
                  name: dcr10-binary
                  path: ./publish
